server:
  port: 9500

logging:
  config: classpath:log4j2.yml   # \u914D\u7F6Elog4j2\u8BFB\u53D6\u7684\u914D\u7F6E\u6587\u4EF6
  file: ../springlogs/provider-9500.log

#\u6570\u636E\u5E93\u8868\u540D\u914D\u7F6E
database:
  #\u5F00\u5173
  isopen: false
  #\u524D\u7F00
  prefix: PM_

spring:
  datasource:
    initialization-mode: ALWAYS
    continue-on-error: true
    data:
      - classpath:schema/data.sql
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  profiles:
    active: "@profileActive@"
  application:
    name: provider-9500
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 3
    host: ${custom.nosql.redis.host}
    port: ${custom.nosql.redis.port}
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
    timeout: 3000
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    addresses: ${custom.nosql.rabbitmq.addresses}
    port: ${custom.nosql.rabbitmq.port}
    username: ${custom.nosql.rabbitmq.username}
    password: ${custom.nosql.rabbitmq.password}
    virtualHost: /
    requestedHeartbeat: 7200
    queues:
      - name: batchport.apply
        exchange-name: batchport.topic.exchange
        bind-name: batchport.apply
    template:
      replyTimeout: 500000

  mvc:
    date-format: yyyy-MM-dd

sharding:
  jdbc:
    datasource:
      names: master,slave0
      master:
        type: org.apache.commons.dbcp.BasicDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: ${custom.db.url}
        username: ${custom.db.username}
        password: ${custom.db.password}
        maxActive: 20
        validationQuery: SELECT 1
        testOnBorrow: false
        timeBetweenEvictionRunsMillis: 300000
        testWhileIdle: true
        minEvictableIdleTimeMillis: 1800000
        initialSize: 5
        minIdle: 3
        maxWait: 30000
      slave0:
        type: org.apache.commons.dbcp.BasicDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: ${custom.db1.url}
        username: ${custom.db1.username}
        password: ${custom.db1.password}
        maxActive: 20
        validationQuery: SELECT 1
        testOnBorrow: false
        timeBetweenEvictionRunsMillis: 300000
        testWhileIdle: true
        minEvictableIdleTimeMillis: 1800000
        initialSize: 5
        minIdle: 3
        maxWait: 30000
    config:
      masterslave:
        load-balance-algorithm-type: ROUND_ROBIN
        name: ds_ms
        master-data-source-name: master
        slave-data-source-names: slave0




