custom:
  app:
    token:
      timeout: 86400
  nosql:
    redis:
      host: 192.168.1.232
      port: 9209
    rabbitmq:
      addresses: 192.168.1.232:9715
      port: 9715
      username: mnet
      password: mnet
  db:
    url: jdbc:mysql://192.168.1.232:3306/mnet?useUnicode=true&characterEncoding=UTF-8
    username: mnet_business
    password: mnet@123
    driver-class-name: com.mysql.jdbc.Driver
    database-platform: org.hibernate.dialect.MySQL5Dialect
  db1:
    url: jdbc:mysql://192.168.1.232:3306/mnet?useUnicode=true&characterEncoding=UTF-8
    username: mnet_business
    password: mnet@123
    driver-class-name: com.mysql.jdbc.Driver
    database-platform: org.hibernate.dialect.MySQL5Dialect
  oauth:
    ip: localhost:9710
    clientId: test
    clientSecret: 123456
  #文件上传配置，保存的路径
  upload:
    #文件保存的路径(服务器主机删的绝对路径，如若没有请新建)
    absolute-path: /home/mnet/montnets/images     
    


eurekaserver:
  ip: localhost
  port: 9709
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false

logging:
  level:
    com.suoju.montnets.common.dao:  DEBUG

token:
  expire:
    seconds: 86400



swagger:
  enable: true

exclude:
  check:
    token:  /loginservice/**,/error/**,/images/**,/webjars/**,/**/doc.html,/**/swagger-resources,/v2/**