server:
  port: 9600

logging:
  config: classpath:log4j2.yml   # \u914D\u7F6Elog4j2\u8BFB\u53D6\u7684\u914D\u7F6E\u6587\u4EF6
  file: ../springlogs/consumer-9600.log

spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #\u914D\u7F6Enacos\u5730\u5740

#\u6D88\u8D39\u8005\u5C06\u8981\u53BB\u8BBF\u95EE\u7684\u5FAE\u670D\u52A1\u540D\u79F0
service-url:
  nacos-user-service: http://nacos-provider

management:
  endpoints:
    web:
      exposure:
        include: '*'
