server:
  port: 9501

logging:
  config: classpath:log4j2.yml
  file: ../springlogs/provider-9501.log

spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'
