spring:
  application:
    name: AppService
custom:
  app:
    token:
      timeout: 86400
  nosql:
    redis:
      host: 10.10.214.67
      port: 6379
    rabbitmq:
      addresses: 10.10.214.67
      port: 5672
      username: mnet
      password: mnet
  db:
    url: jdbc:mysql://10.10.214.67:3306/mnet?useUnicode=true&characterEncoding=UTF-8
    username: mnet_business
    password: mnet@123
    driver-class-name: com.mysql.jdbc.Driver
    database-platform: org.hibernate.dialect.MySQL5Dialect
  db1:
    url: jdbc:mysql://10.10.214.67:3306/mnet?useUnicode=true&characterEncoding=UTF-8
    username: mnet_business
    password: mnet@123
    driver-class-name: com.mysql.jdbc.Driver
    database-platform: org.hibernate.dialect.MySQL5Dialect
  oauth:
    ip: 10.10.214.68:9710
    clientId: test
    clientSecret: test
  #文件上传配置，保存的路径
  upload:
    #文件保存的路径(服务器主机删的绝对路径，如若没有请新建)
    absolute-path: /home/mnet/montnets/images

eurekaserver:
  ip: 10.10.214.68
  port: 9709


token:
  expire:
    seconds: 86400



swagger:
  enable: false


exclude:
  check:
    token:  /loginservice/**,/error/**,/images/**