server:
  port: 9810

logging: 
  config: classpath:log4j2.yml   # 配置log4j2读取的配置文件
  file: ../springlogs/eurekaserver.log

spring:
  profiles:
    active: "@profileActive@"
  application:
    name: EurekaServer

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
      health:
        show-details: ALWAYS


eureka:
  instance:
    hostname: ${eurekaserver.ip}
  client:
    #表示是否将自己注册到Eureka Server，默认为true。
    register-with-eureka: false
    #表示是否从Eureka Server获取注册信息，默认为true。
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://${eurekaserver.ip}:${server.port}/eureka/